### ISSUE TITLE
Move reusable nextflow functions to a common repo

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo-workflows/gatk-tools#46]
This is typically Nextflow function like getSecondaryFiles [here](https://github.com/icgc-argo/gatk-tools/blob/0acb8cea265486b3270c77bf211045696da37f80/tools/gatk-base-recalibrator/gatk-base-recalibrator.nf#L36-L49)

With these functions centrally managed, we can import them as needed.

**Comment by junjun-zhang** [comment]
This is now trieval to do using WFPM https://github.com/icgc-argo/wfpm. These reusable functions can be easily put in a package, then import into wherever needs

**Comment by lindaxiang** [comment]
Not to do.
